{% set name = "magic-wormhole" %}
{% set version = "0.14.0" %}
{% set sha256 = "6104ff2ce1223bf8fefc3a7a2a3bca0dddb86e008b21b6f47543dd74ab18db3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/warner/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - wormhole = wormhole.cli.cli:wormhole

requirements:
  host:
    - python
    - pip
  run:
    - python
    - spake2 ==0.8
    - pynacl
    - six
    - attrs >=16.3.0
    - twisted >=17.5.0
    - autobahn >=0.14.1
    - automat
    - hkdf
    - tqdm >=4.13.0
    - click
    - humanize
    - service_identity

test:
  commands:
    - wormhole --version
    - wormhole --help
  imports:
    - wormhole

about:
  home: http://github.com/warner/magic-wormhole
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Get things from one computer to another, safely.

  description: |
    This package provides a library and a command-line tool named wormhole, 
    which makes it possible to get arbitrary-sized files and directories (or 
    short pieces of text) from one computer to another. The two endpoints are 
    identified by using identical "wormhole codes": in general, the sending 
    machine generates and displays the code, which must then be typed into 
    the receiving machine.

  doc_url: https://magic-wormhole.readthedocs.io/en/latest/
  dev_url: http://github.com/warner/magic-wormhole

extra:
  recipe-maintainers:
    - CJ-Wright
