travis:
  secure:
    BINSTAR_TOKEN: vnn1qKYVEEjd+NhR7Vnijk1bAo0AhlUQPh6EDENbjNLaDqhrnCsxNdcfWAA0uVEkgB0gMJ3/MhP10tW1POgGotx+4avmcxdUJUBZQXkHJykJgu7mnl4DueKzd2+lAQ8JP7zZL0LFkLuX0Mk3IIJYZPGRkGdGppeoLrgmMt7pl8nhfOVXK2gyteAQw6X4K48UbNKzZGnetPhfDc6/+d47KW6EkcOV6Rg+KAiXQuXqlZ4cNNw49IFjN6y0Yaw5BsUPEluwy5OnjyabTz1IfnaleJ9RfvcIQMQkP6bB4BhBX8wQmQbzS1ScFstP1H+Bn1Z2HKWhGKXHIJL/et//DV+S36rQ1S9ayf+/fkR9nmVQpn6CcksC83fWajDOUhK1Cs3+0nMBIB70lcIRbX+j8rj9+4BOBO+XM2FAgfQGsbdzLBC/ih7S6MBdqwyfDaiMKeYTOqrFQ7RaAOzvmwuGUkNRc/8cPhogXTNaLqOWNCAnyByy5n/mGTUYC0kDm5FILxK9PjGnIdSjyX8ViZwgN1kIbZQPDBpo/CT0l8mh7OT/7qjab3syoaaVABnBJrGc5jGSdBdyIq70WmnvsrVht+wISZi8hAjuxN5FNbtphcZzK/dz8Jvpgy9TIQFj2QOvIwG4YKedXBlGTPRwxV+TXS6cpgfCEYj9rYKO96RSEqeg+Rc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
